// src/lib/quotes.ts
export const studyQuotes: string[] = [
  "Oh look, Einstein finally opened a book. Miracles do happen!",
  "Studying now? The exam just called — it’s already disappointed in you.",
  "Your syllabus is thicker than your confidence.",
  "You treat deadlines like mere suggestions, don’t you?",
  "Welcome to the study table — better late than graduated.",
  "The syllabus isn’t going to study itself, but nice try ignoring it!",
  "You're so late even the backbenchers are judging you.",
  "Burning the midnight oil? More like microwaving regrets.",
  "If procrastination was a subject, you’d top it.",
  "You’re so late to study, even your books gave up and filed for abandonment.",
  "At this point, even Google is tired of helping you.",
  "Trying to cover 5 units in 2 hours? Bold strategy.",
  "You opened your books so late, they’ve turned vintage.",
  "You skipped the entire semester but now want divine intervention?",
  "Exams tomorrow, and you're still figuring out chapter names?",
  "Don't worry, panic is a great study partner.",
  "You’re not late — you’re on 'academic suicide' mode.",
  "Trying to study now is like trying to fill a bucket with holes.",
  "Your syllabus is looking at you like: 'Who are you again?'",
  "You're studying like it’s a hobby, not a necessity.",
  "You study like Netflix gives you extra marks.",
  "Even your highlighters are confused — 'We doing this now?'",
  "You treat study time like a cheat day.",
  "You skipped so many classes, even the teacher forgot your name.",
  "Is this your study plan or your wishful thinking?",
  "Your notes have more doodles than definitions.",
  "You think you’re cramming, but your brain is buffering.",
  "If stress-bingeing was productive, you'd have a PhD by now.",
  "Last-minute prep? More like last-hope prep.",
  "You Googled 'how to pass without studying,' didn’t you?",
  "You believe in miracles more than your textbooks.",
  "Your study table looks like a crime scene of neglect.",
  "At this point, even caffeine can’t save you.",
  "Why study now when failure is already emotionally prepared?",
  "If only staring at books transferred knowledge...",
  "Even the exam paper is going to feel sorry for you.",
  "You studied so late, even your syllabus went out of syllabus.",
  "Trying to revise now is like reviving a dead phone without a charger.",
  "You’re not late, you’re just on a scenic route to failure.",
  "Your exam prep is the academic version of a Hail Mary.",
  "That’s not studying — that’s just skimming through regret.",
  "At least your overconfidence stayed consistent all semester.",
  "You're so underprepared, even the MCQs look like riddles.",
  "Why study now? Just wing it and hope for a plot twist.",
  "You opened the book and the book gasped in shock.",
  "You’re so late even your memory gave up.",
  "Your GPA is about to ghost you.",
  "That’s not a revision plan — that’s a panic plan.",
  "Cramming now? Hope your memory has wings.",
  "Study? I thought you were just scrolling notes for decoration.",
  "If your effort was a graph, it would be a flatline.",
  "Books are like friends — ignore them long enough and they stop helping.",
  "Studying now is like going to the gym after eating the buffet.",
  "Your sleep schedule is waving the white flag.",
  "You said you’d start yesterday. Guess what? It’s still yesterday.",
  "You revise chapters like you owe them money.",
  "Plot twist: you’re not passing by vibes alone.",
  "Your brain is still on summer break.",
  "At this point, even your luck is asking for a backup plan.",
  "Studying this late? Just submit a 'Sorry' letter with the answer sheet.",
  "Your books are fresh — because you never opened them.",
  "Cramming a semester in one night? Ambitious chaos.",
  "That’s not a syllabus — that’s a mountain of missed opportunity.",
  "You prepped more for a meme than for this exam.",
  "Studying now is like practicing swimming during a flood.",
  "Your syllabus just texted: 'Good luck, loser.'",
  "The only thing you’ve revised properly is your playlist.",
  "You didn’t study — you just stared at pages hoping for osmosis.",
  "Your concentration level is in airplane mode.",
  "You prepared so late, the universe is confused.",
  "The only thing you’ve completed is your series binge.",
  "If exams were based on intentions, you'd ace them all.",
  "The paper's going to ask questions — not for forgiveness.",
  "Studying one night before is a personality trait now.",
  "You’re not revising, you’re speedrunning despair.",
  "Syllabus: 1000 pages. Time left: 2 hours. Strategy: vibes.",
  "You treat deadlines like rumors.",
  "Your exam prep is basically a motivational poster in denial.",
  "You procrastinated so hard, even time gave up chasing you.",
  "At this point, cheat sheets need cheat sheets.",
  "You study like it's a side quest.",
  "Books are shocked you still remember their location.",
  "Even your calculator's judging your choices.",
  "Your brain is on low battery and you forgot the charger.",
  "That’s not exam prep — that’s academic cosplay.",
  "You said you'd study after 5 minutes — 5 weeks ago.",
  "You're trying to build Rome in one night now?",
  "Your books aged more than your maturity this semester.",
  "Even AI can't help you now.",
  "Your syllabus is giving you the silent treatment.",
  "You're so late, even your future self is disappointed.",
  "That revision plan is just wishful thinking in a table format.",
  "You crammed so hard your brain called for a refund.",
  "That last-minute prep is pure adrenaline and delusion.",
  "Even the invigilator will look at you like 'bless this soul.'",
  "You’re studying like it’s a speed date with destiny.",
  "Time management? More like time massacre.",
  "Your motivation showed up... after the exam schedule.",
  "You believe in luck more than logic.",
  "At this point, your grades will need thoughts and prayers.",
];
